### ISSUE TITLE
panic: runtime error on iplocation.mmdb

### ISSUE THREAD

**Issue by RandomUser1215R** [ipinfo/mmdbctl#33]
Hello, 
I am running errors using mmdbctl_1.4.4_linux_386 with iplocation.mmdb

```
./mmdbctl_1.4.4_linux_386 verify iplocation.mmdb
panic: runtime error: index out of range [654620380] with length 654620376

goroutine 1 [running]:
github.com/oschwald/maxminddb-golang.nodeReader32.readRight(...)
        /home/runner/go/pkg/mod/github.com/oschwald/maxminddb-golang@v1.12.0/node.go:54
github.com/oschwald/maxminddb-golang.(*Networks).Next(0x9c50090)
        /home/runner/go/pkg/mod/github.com/oschwald/maxminddb-golang@v1.12.0/traverse.go:142 +0x195
github.com/oschwald/maxminddb-golang.(*verifier).verifySearchTree(0x9c56f08)
        /home/runner/go/pkg/mod/github.com/oschwald/maxminddb-golang@v1.12.0/verifier.go:106 +0x7e
github.com/oschwald/maxminddb-golang.(*verifier).verifyDatabase(0x9c56f08)
        /home/runner/go/pkg/mod/github.com/oschwald/maxminddb-golang@v1.12.0/verifier.go:90 +0x25
github.com/oschwald/maxminddb-golang.(*Reader).Verify(0x9c00180)
        /home/runner/go/pkg/mod/github.com/oschwald/maxminddb-golang@v1.12.0/verifier.go:21 +0x51
github.com/ipinfo/mmdbctl/lib.CmdVerify({0x0}, {0x9c10438, 0x1, 0x1}, 0x825e31c)
        /home/runner/work/mmdbctl/mmdbctl/lib/cmd_verify.go:49 +0x142
main.cmdVerify()
        /home/runner/work/mmdbctl/mmdbctl/cmd_verify.go:35 +0x100
main.main()
        /home/runner/work/mmdbctl/mmdbctl/main.go:42 +0x141
```

**Comment by curious-bug** [comment]
I've run into the same error message.
Different index number (215694220) but the value is off by 4 as well (length 215694216)

**Comment by oschwald** [comment]
This issue was fixed in [this commit](https://github.com/oschwald/maxminddb-golang/pull/159/commits/c06679525eab07f5cb7c36a8c627a7a97f21fd41) in the underlying database reader. The bug was caused by integer overflow when running on 32-bit architectures.

Unless you specifically need 32-bit compatibility, I recommend using the `amd64` binary available on the releases page. The `386` (32-bit) executable is limited to 4GB of addressable memory and may encounter other memory-related issues.

**Comment by curious-bug** [comment]
We switched to the 64 bit release of 1.4.6 and the issue is resolved, thank you
